enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
excluded-patches = "'GmsCore support'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Infinity]
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit-plus/"
patcher-args = "-e 'Spoof client' -Oclient-id=VhWfJfr4qIV1mYQnRTOBzw"

[Spotify]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Twitch]
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
arch = "arm64-v8a"
